In [1]:
# ================================================================
# 4. Create a transformer from scratch using the Pytorch librar
# ================================================================

# ================================================================
# INSTALLATION COMMAND
# ================================================================
#
# pip install torch
#
# ================================================================

# ================================================================
# IMPORT LIBRARIES
# ================================================================

import torch
import torch.nn as nn
import torch.nn.functional as F

# ================================================================
# SYSTEM HEADER
# ================================================================

print("\n" + "="*70)
print("      SIMPLE TRANSFORMER BLOCK USING PYTORCH")
print("="*70)

# ================================================================
# STEP 1 : INPUT EMBEDDINGS
# ================================================================

# 2 words with 3 features each

X = torch.tensor([
    [1.0, 0.0, 1.0],
    [0.0, 1.0, 1.0]
])

print("\nINPUT EMBEDDINGS")
print("-"*40)

print(X)

# ================================================================
# STEP 2 : POSITIONAL ENCODING
# ================================================================

# Simple Positional Encoding

positional_encoding = torch.tensor([
    [0.1, 0.0, 0.1],
    [0.0, 0.1, 0.1]
])

# Add positional information
X = X + positional_encoding

print("\nPOSITIONAL ENCODING")
print("-"*40)

print(positional_encoding)

print("\nINPUT AFTER POSITIONAL ENCODING")
print("-"*40)

print(X)

# ================================================================
# STEP 3 : CREATE QUERY, KEY, VALUE MATRICES
# ================================================================

# Linear layers for Q, K, V

Wq = nn.Linear(3, 3, bias=False)

Wk = nn.Linear(3, 3, bias=False)

Wv = nn.Linear(3, 3, bias=False)

# ================================================================
# STEP 4 : COMPUTE QUERY, KEY, VALUE
# ================================================================

Q = Wq(X)

K = Wk(X)

V = Wv(X)

print("\nQUERY MATRIX (Q)")
print("-"*40)

print(Q)

print("\nKEY MATRIX (K)")
print("-"*40)

print(K)

print("\nVALUE MATRIX (V)")
print("-"*40)

print(V)

# ================================================================
# STEP 5 : SCALED DOT-PRODUCT ATTENTION
# ================================================================

# Scaling Factor
d_k = K.size(-1)

# Attention Scores
scores = torch.matmul(Q, K.T) / (d_k ** 0.5)

print("\nSCALED ATTENTION SCORES")
print("-"*40)

print(scores)

# ================================================================
# STEP 6 : SOFTMAX ATTENTION WEIGHTS
# ================================================================

attention_weights = F.softmax(scores, dim=1)

print("\nATTENTION WEIGHTS")
print("-"*40)

print(attention_weights)

# ================================================================
# STEP 7 : ATTENTION OUTPUT
# ================================================================

attention_output = torch.matmul(attention_weights, V)

print("\nATTENTION OUTPUT")
print("-"*40)

print(attention_output)

# ================================================================
# STEP 8 : FEED FORWARD NETWORK
# ================================================================

feed_forward = nn.Sequential(

    nn.Linear(3, 6),

    nn.ReLU(),

    nn.Linear(6, 3)

)

ffn_output = feed_forward(attention_output)

print("\nFEED FORWARD NETWORK OUTPUT")
print("-"*40)

print(ffn_output)

# ================================================================
# STEP 9 : FINAL TRANSFORMER OUTPUT
# ================================================================

print("\n" + "="*70)
print(" FINAL TRANSFORMER OUTPUT")
print("="*70)

print(ffn_output)

# ================================================================
# PROGRAM END
# ================================================================

print("\nProgram Executed Successfully.")
print("="*70)


      SIMPLE TRANSFORMER BLOCK USING PYTORCH

INPUT EMBEDDINGS
----------------------------------------
tensor([[1., 0., 1.],
        [0., 1., 1.]])

POSITIONAL ENCODING
----------------------------------------
tensor([[0.1000, 0.0000, 0.1000],
        [0.0000, 0.1000, 0.1000]])

INPUT AFTER POSITIONAL ENCODING
----------------------------------------
tensor([[1.1000, 0.0000, 1.1000],
        [0.0000, 1.1000, 1.1000]])

QUERY MATRIX (Q)
----------------------------------------
tensor([[ 0.1116, -0.6775, -0.2279],
        [ 0.3246, -0.2858, -0.4873]], grad_fn=<MmBackward0>)

KEY MATRIX (K)
----------------------------------------
tensor([[ 0.1124,  0.9470, -0.4064],
        [ 0.4165,  0.8509, -0.8085]], grad_fn=<MmBackward0>)

VALUE MATRIX (V)
----------------------------------------
tensor([[ 0.8505,  0.1137,  0.5941],
        [ 0.0748, -0.2110,  0.3014]], grad_fn=<MmBackward0>)

SCALED ATTENTION SCORES
----------------------------------------
tensor([[-0.3097, -0.1996],
        [-0.0

# Theory

Transformer is a deep learning architecture introduced for handling sequential data efficiently in Natural Language Processing (NLP). Unlike traditional Recurrent Neural Networks (RNNs) and Long Short-Term Memory (LSTM) networks, transformers process all words in parallel instead of sequentially. This makes transformers faster, more efficient, and highly effective for large-scale NLP tasks.

Transformers are widely used in:
- Machine Translation
- Text Summarization
- Chatbots
- Sentiment Analysis
- Question Answering Systems
- Large Language Models such as GPT and BERT

The transformer architecture mainly relies on a mechanism called **Self-Attention**.

---

# Self-Attention Mechanism

Self-attention helps the model understand relationships between words in a sentence by assigning importance scores to different words.

For example, in the sentence:

`The cat sat on the mat because it was tired.`

the word `it` refers to `cat`.

Self-attention helps the transformer understand such contextual relationships.

---

# Components of Transformer

A transformer mainly consists of the following components:

- Input Embeddings
- Positional Encoding
- Query Matrix (Q)
- Key Matrix (K)
- Value Matrix (V)
- Scaled Dot-Product Attention
- Softmax Function
- Feed Forward Neural Network

---

# 1. Input Embeddings

Words are first converted into numerical vector representations called embeddings.

Example:

| Word | Embedding Vector |
|---|---|
| NLP | [1.0, 0.5, 0.2] |
| AI | [0.8, 0.1, 0.9] |

These embeddings help the model process textual information numerically.

---

# 2. Positional Encoding

Transformers process words in parallel and do not naturally understand word order. Therefore, positional encoding is added to embeddings to provide sequence information.

Example:

| Word Position | Positional Information |
|---|---|
| Word 1 | [0.1, 0.0, 0.1] |
| Word 2 | [0.0, 0.1, 0.1] |

Positional encoding helps the transformer understand the order of words in a sentence.

---

# 3. Query, Key and Value Matrices

Transformer creates three matrices from the input embeddings:

- Query Matrix (Q)
- Key Matrix (K)
- Value Matrix (V)

These matrices are generated using linear transformations.

## Purpose

| Matrix | Purpose |
|---|---|
| Query (Q) | What the current word is searching for |
| Key (K) | What information each word contains |
| Value (V) | Actual information passed forward |

---

# 4. Scaled Dot-Product Attention

Attention scores are calculated using Query and Key matrices.

### Formula

Attention(Q,K,V) = softmax((QKᵀ) / √dₖ)V

Where:
- Q = Query Matrix
- K = Key Matrix
- V = Value Matrix
- dₖ = Dimension of Key Matrix

The scaling factor √dₖ prevents extremely large values during multiplication.

Attention helps the model focus on important words in the sequence.

---

# 5. Softmax Function

The softmax function converts attention scores into probability values between 0 and 1.

### Formula

Softmax(xᵢ) = eˣⁱ / Σeˣʲ

The probabilities determine how much attention should be given to each word.

---

# 6. Feed Forward Neural Network (FFN)

After attention computation, the output is passed through a Feed Forward Neural Network.

The FFN:
- learns complex patterns
- improves feature representation
- increases model capability

In this practical, the feed-forward network consists of:
- Linear Layer
- ReLU Activation Function
- Linear Layer

---

# Libraries Used

| Library | Purpose |
|---|---|
| torch | Tensor operations and deep learning |
| torch.nn | Neural network layers |
| torch.nn.functional | Activation functions and softmax |

---

# PyTorch

PyTorch is an open-source deep learning framework developed by Meta (Facebook). It is widely used for:
- deep learning
- NLP
- computer vision
- neural network implementation

PyTorch provides:
- tensor operations
- automatic differentiation
- GPU acceleration
- neural network modules

---

# Algorithm

1. Import required PyTorch libraries.  
2. Create input embedding vectors.  
3. Add positional encoding to embeddings.  
4. Create Query, Key, and Value matrices using linear layers.  
5. Compute scaled attention scores.  
6. Apply softmax function to generate attention weights.  
7. Generate attention output using Value matrix.  
8. Pass output through Feed Forward Neural Network.  
9. Display final transformer output.  

---

# Advantages

- Processes sequences in parallel
- Faster than RNN and LSTM
- Captures long-range dependencies
- Highly efficient for large datasets
- Improves contextual understanding
- Scalable for large NLP models

---

# Applications

- ChatGPT
- BERT
- Google Translate
- Text Summarization
- Speech Recognition
- Recommendation Systems
- Sentiment Analysis
- Machine Translation
- Question Answering Systems

---

# Conclusion

In this practical, a simple transformer block was implemented using the PyTorch library. The transformer model used Query, Key, and Value matrices along with scaled dot-product attention and a feed-forward neural network to process input embeddings. Positional encoding was also added to preserve sequence information. Transformers are one of the most important architectures in modern Natural Language Processing and form the foundation of advanced AI systems such as GPT and BERT.


# WORKING

# 1. Input Embeddings Creation

Input words are represented as numerical vectors called embeddings.

Example:

```text id="i84xl8"
[1.0, 0.0, 1.0]
[0.0, 1.0, 1.0]
```

These vectors act as the input to the transformer.

---

# 2. Positional Encoding

Since transformers process all words simultaneously, positional encoding is added to preserve word order information.

The positional vectors are added to the input embeddings so that the model understands sequence positions.

---

# 3. Query, Key, and Value Matrix Generation

Three matrices are created using PyTorch linear layers:

* Query Matrix (Q)
* Key Matrix (K)
* Value Matrix (V)

These matrices help the transformer determine:

* what information to search for
* what information is available
* what information should be passed forward

---

# 4. Attention Score Calculation

Attention scores are computed using matrix multiplication between Query and Key matrices.

Formula used:

Scores = \frac{QK^T}{\sqrt{d_k}}

This step measures the relationship between words.

---

# 5. Softmax Attention Weights

Softmax function converts attention scores into probability values between 0 and 1.

These attention weights determine the importance of each word in the sequence.

---

# 6. Attention Output Generation

The attention weights are multiplied with the Value matrix to generate the attention output.

This output contains contextual information learned by the transformer.

---

# 7. Feed Forward Neural Network

The attention output is passed through a Feed Forward Neural Network consisting of:

* Linear Layer
* ReLU Activation
* Linear Layer

This helps the model learn complex patterns and improve feature representation.

---

# 8. Final Transformer Output

The final transformed output vectors are displayed after attention and feed-forward processing.

These vectors represent processed contextual information.

---

# Overall Summary

This practical demonstrates the core working of a Transformer architecture using PyTorch, including:

* input embeddings
* positional encoding
* Query-Key-Value mechanism
* scaled dot-product attention
* softmax attention
* feed-forward neural network

The practical provides a foundational understanding of how modern transformer-based NLP models such as GPT and BERT process textual information.
